### ISSUE TITLE
function scaling takes unnecessary parameters

### ISSUE THREAD

**Issue by marianoju** [maddosz12/pytorch_team_2#12]
https://github.com/maddosz12/pytorch_team_2/blob/f04fff00b5240b5ec1b0dcd49ce4addb56193fbb/features/__init__.py#L11

Die Funktion ```scaling``` nimmt 5 Parameter, verarbeitet aber nur drei (```method```, ```X_train```, ```X_test```). ```y_test``` und ```y_train``` sind hier überflüssig.

**Comment by Spabst15** [comment]
habe einen Pull request dafür erstellt: https://github.com/maddosz12/pytorch_team_2/pull/14
