### ISSUE TITLE
master not running

### ISSUE THREAD

**Issue by Spabst15** [maddosz12/pytorch_team_2#42]
Bei mir läuft der aktuelle Master nicht:
No such file or directory: 'results/test_errors_dtwpf.csv'

**Comment by marianoju** [comment]
Ein Problem für @fsmanuel und @maddosz12

**Comment by marianoju** [comment]
Has the issue been resolved?

**Comment by maddosz12** [comment]
Ja, das issue hatte nichts mit dem Projekt zu tun. Sophies PyCharm settings für das Ausführen von dem Projekt war falsch Konfiguriert...
