### ISSUE TITLE
Inconvenient format for comment

### ISSUE THREAD

**Issue by maddosz12** [maddosz12/pytorch_team_2#43]
https://github.com/maddosz12/pytorch_team_2/blob/b6a10ec2e25e5c331c68c855c30f1e015804b117/projects/housing/housing.py#L66

Write 

# TODO: Stuff to do

instead. This will be picked up by the IDE

**Comment by marianoju** [comment]
Good one. Thanks! :+1:

**Comment by marianoju** [comment]
Implemented with #47
