### ISSUE TITLE
Move models to separate forlders

### ISSUE THREAD

**Issue by maddosz12** [maddosz12/pytorch_team_2#44]
https://github.com/maddosz12/pytorch_team_2/blob/b6a10ec2e25e5c331c68c855c30f1e015804b117/lib/models/dtree_with_pruning.py#L1

It might make sense to move models to separate folders. This way everything regarding trees (pruning/etc) is part of that folder and not intermixed with the other models.

**Comment by marianoju** [comment]
Do you mean: “... to move *each* model into a *dedicated* folder”?
