### ISSUE TITLE
Not an ML feature

### ISSUE THREAD

**Issue by maddosz12** [maddosz12/pytorch_team_2#45]
https://github.com/maddosz12/pytorch_team_2/blob/b6a10ec2e25e5c331c68c855c30f1e015804b117/lib/features/tree_to_png.py#L1

This should be part of some utility file or part of the evaluation folder.

**Comment by marianoju** [comment]
:+1: 
I will move `tree_to_png.py` to `pytorch_team_2/lib/evaluation`.
