### ISSUE TITLE
Rename to housing_preprocessing

### ISSUE THREAD

**Issue by maddosz12** [maddosz12/pytorch_team_2#46]
https://github.com/maddosz12/pytorch_team_2/blob/b6a10ec2e25e5c331c68c855c30f1e015804b117/lib/features/preprocessing.py#L1

While this is preprocessing code, it is specific to the housing data set and does not contain general functions, hence it makes sense to rename the file.

**Comment by marianoju** [comment]
We are on it.

**Comment by marianoju** [comment]
issue resolved with [`commit 1d3e0785c84b5d0e3fbd6aec28d90627edcbf6bb`](https://github.com/maddosz12/pytorch_team_2/commit/1d3e0785c84b5d0e3fbd6aec28d90627edcbf6bb)

**Comment by marianoju** [comment]
Solved with #47
